DGin/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('qna/', include('qna.urls')),
    path('accounts/',include('accounts.urls')),
    path('users/',include('users.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/codelion-django-main/5_댓글/blogproject/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),

    # html form 을 이용해 블로그 객체 만들기
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # django form을 이용해 블로그 객체 만들기
    path('formcreate/', views.formcreate, name='formcreate'),

    # django modelform을 이용해 블로그 객체 만들기
    path('modelformcreate/', views.modelformcreate, name='modelformcreate'),

    # 댓글 처리 url
     path('create_comment/<int:blog_id>', views.create_comment , name="create_comment")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path
from .views import *

app_name = "qna"
urlpatterns = [
    path('majorlist/', majorList, name="majorList"),
    path('nonmajorlist/', nonmajorList, name="nonmajorList"),
    
    path('<int:id>', detail, name="detail"),
    path('major_new/', major_new, name="major_new"),
    path('nonmajor_new/', nonmajor_new, name="nonmajor_new"),
    path('major_create/', major_create, name="major_create"),
    path('nonmajor_create/', nonmajor_create, name="nonmajor_create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<str:question_id>/create_answer/', create_answer, name="create_answer"),
    path('<str:question_id>/edit_answer/<str:answer_id>', edit_answer, name="edit_answer"),
    path('<str:question_id>/update_answer/<str:answer_id>', update_answer, name="update_answer"),
    path('<str:question_id>/delete_answer/<str:answer_id>', delete_answer, name="delete_answer"),

    path('<int:id>/likes/', likes, name="likes"),
    path('<int:question_id>/select/<int:answer_id>', select, name="select"),
    path('search/', search, name='search'),
]

users/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = "users"
urlpatterns = [
  path('mypage/', mypage, name="mypage"),
  path('mypage_new/', mypage_new, name="mypage_new"),
  path('mypage_create/', mypage_create, name="mypage_create"),
  path('mypage_edit/', mypage_edit, name="mypage_edit"),
  path('mypage_update/', mypage_update,name="mypage_update"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

DGin/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from qna.models import Question, Profile, Department, Answer

def mypage(request):
   #내가 쓴 글 필터링하는 함수
   user_profile = get_object_or_404(Profile, user = request.user)
   questions=Question.objects.filter(writer=user_profile)
   user_department = user_profile.department.all()
   answers=Answer.objects.filter(writer=user_profile)
   count_q = questions.count()
   count_a = answers.count()
   return render(request,'users/mypage.html',{
      'questions':questions,
      'profile':user_profile,
      'user_department':user_department,
      'answers': answers,
      'count_q': count_q,
      'count_a': count_a,
      })


def mypage_new(request):
   return render(request, 'users/mypage_new.html')



# Mypage에 쓴 자신 정보 수정하고 생성하는 함수/수정하면 mypage로 돌아가게
def mypage_create(request):
    new_mypage = get_object_or_404(Profile, user = request.user)
    new_mypage.introduction = request.POST['intro']
    #Profile 모델에서 자기소개를 introduction으로 선언해줬으니까 .introduction으로 불러와야 돼
    new_mypage.image = request.FILES.get('profile_image')
    new_mypage.save()
    return redirect('users:mypage')

def mypage_edit(request):
   #질문 작성 crud에서는 질문의 id를 가져와서 수정했던거에 비해 프로필은 request.user로 현재 로그인된 계정을 불러올수 있으니까 따로 id를 선언해줄 필요 없어   
   departments = Department.objects.all()
   myprofile = get_object_or_404(Profile, user=request.user)
   mine =  myprofile.department.all()
   plus_result = []
   minus_result = []
   for d in departments:
      if d in mine:
         minus_result.append(d)
      else:
         plus_result.append(d)
   return render(request,'users/mypage_edit.html',{
      'plus_departments':plus_result,   
      'minus_departments':minus_result,
      'profile':myprofile,
      })

def mypage_update(request):
   update_mypage = get_object_or_404(Profile, user = request.user)
   update_mypage.introduction = request.POST['intro']
   update_mypage.image = request.FILES.get('profile_image')
   update_mypage.name = request.POST['name']
   if request.POST['plus_department'] != '':
      department = Department.objects.get(name = request.POST['plus_department'])
      update_mypage.department.add(department)
   if request.POST['minus_department'] != '':
      department = Department.objects.get(name = request.POST['minus_department'])
      update_mypage.department.remove(department)
   grade = request.POST['grade']

   FRESHMAN = '1학년'
   SOPHOMORE = '2학년'
   JUNIOR = '3학년'
   SENIOR = '4학년'
   POSTGRAD = '대학원생'
   GRADUATED = '졸업생'
   if grade == "1":
      update_mypage.year_in_school = FRESHMAN
   elif grade == "2":
      update_mypage.year_in_school = SOPHOMORE
   elif grade == "3":
      update_mypage.year_in_school = JUNIOR
   elif grade == "4":
      update_mypage.year_in_school = SENIOR 
   elif grade == "pg":
      update_mypage.year_in_school = POSTGRAD 
   elif grade == "gr":
      update_mypage.year_in_school = GRADUATED
   else :
      pass
   update_mypage.save()
   return redirect('users:mypage')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from qna.models import Question, Profile, Department, Answer

def mypage(request):
   #내가 쓴 글 필터링하는 함수
   user_profile = get_object_or_404(Profile, user = request.user)
   questions=Question.objects.filter(writer=user_profile)
   user_department = user_profile.department
   user_sub_department = user_profile.sub_department
   answers=Answer.objects.filter(writer=user_profile)
   count_q = questions.count()
   count_a = answers.count()
   return render(request,'users/mypage.html',{
      'questions':questions,
      'profile':user_profile,
      'user_department':user_department,
      'user_sub_department':user_sub_department,
      'answers': answers,
      'count_q': count_q,
      'count_a': count_a,
      })


def mypage_new(request):
   return render(request, 'users/mypage_new.html')



# Mypage에 쓴 자신 정보 수정하고 생성하는 함수/수정하면 mypage로 돌아가게
def mypage_create(request):
    new_mypage = get_object_or_404(Profile, user = request.user)
    new_mypage.introduction = request.POST['intro']
    #Profile 모델에서 자기소개를 introduction으로 선언해줬으니까 .introduction으로 불러와야 돼
    new_mypage.image = request.FILES.get('profile_image')
    new_mypage.save()
    return redirect('users:mypage')

def mypage_edit(request):
   #질문 작성 crud에서는 질문의 id를 가져와서 수정했던거에 비해 프로필은 request.user로 현재 로그인된 계정을 불러올수 있으니까 따로 id를 선언해줄 필요 없어   
   departments = Department.objects.all()
   myprofile = get_object_or_404(Profile, user=request.user)
   user_department =  myprofile.department
   user_sub_department = myprofile.sub_department
   department_list = departments
   sub_department_list = departments
   return render(request,'users/mypage_edit.html',{
      'user_department':user_department,   
      'user_sub_department':user_sub_department,
      'profile':myprofile,
      'department_list':department_list,
      'sub_department_list':sub_department_list,
      })

def mypage_update(request):
   update_mypage = get_object_or_404(Profile, user = request.user)
   update_mypage.introduction = request.POST['intro']
   update_mypage.image = request.FILES.get('profile_image')
   update_mypage.name = request.POST['name']
   if request.POST['department'] != '':
      update_mypage.department = Department.objects.get(name = request.POST['department'])
   if request.POST['sub_department'] != '':
      update_mypage.sub_department = Department.objects.get(name = request.POST['sub_department'])
   grade = request.POST['grade']

   FRESHMAN = '1학년'
   SOPHOMORE = '2학년'
   JUNIOR = '3학년'
   SENIOR = '4학년'
   POSTGRAD = '대학원생'
   GRADUATED = '졸업생'
   if grade == "1":
      update_mypage.year_in_school = FRESHMAN
   elif grade == "2":
      update_mypage.year_in_school = SOPHOMORE
   elif grade == "3":
      update_mypage.year_in_school = JUNIOR
   elif grade == "4":
      update_mypage.year_in_school = SENIOR 
   elif grade == "pg":
      update_mypage.year_in_school = POSTGRAD 
   elif grade == "gr":
      update_mypage.year_in_school = GRADUATED
   else :
      pass
   update_mypage.save()
   return redirect('users:mypage')

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}


{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile_style.css' %}">
<!-- mypage -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="main-content">
      <div class="container mt-7">
        <!-- Table -->
        <!-- <h2 class="mb-5">개인 프로필</h2> -->
        <br>
        <br>
        <div class="box">
          <div class="col-xl-8 m-auto order-xl-2 mb-5 mb-xl-0">
            <div class="card card-profile shadow">
              <div class="row justify-content-center">
                <div class="col-lg-3 order-lg-2">
                  <div class="card-profile-image">
                    <a href="#">
                      {% if profile.image  %}
                      <img src="{{ profile.image.url }}" class="rounded-circle">
                      {% else %}
                      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtB6rXnf0CcbxpTidJShuQWRvubJ-tDJS41O9C8IdKGeKxAk7Bnl2A2Vf-iB3Ef-oskVM&usqp=CAU" class="rounded-circle">
                      {% endif %}
                    </a>
                  </div>
                </div>
              </div>
              
              <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
                <div class="d-flex justify-content-between">
                  <!-- <a href="#" class="btn btn-sm btn-info mr-4">Connect</a> -->
                  <a href="{% url 'users:mypage_edit' %}" class="btn btn-sm btn-default float-right">프로필 수정하기</a>
                </div>
              </div>
              <div class="card-body pt-0 pt-md-4">
                <div class="row">
                  <div class="col">
                    <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                      <div>
                        <span class="heading">{{count_q}}</span>
                        <span class="description">작성한 질문 수</span>
                      </div>
                      <div>
                        <span class="heading">{{count_a}}</span>
                        <span class="description">작성한 답변 수</span>
                      </div>
                      <!-- <div>
                        <span class="heading">89</span>
                        <span class="description">Comments</span>
                      </div> -->
                    </div>
                  </div>
                </div>
                <hr class="my-4">
                <style>
                </style>
                <div class="info">
                  <div class="profilebox" style="padding-left: 6rem;">
                    <div class="nickname">
                      <div class="info-title">
                          <div class="title2">닉네임 &nbsp;|</div>
                          <span class="info-text">
                              <I>{{profile}}</I>
                          </span>
                      </div>
                    </div>
                    <div class="major">
                      <div class="info-title">
                          <div class="title2" id="major">전　공 &nbsp;|</div>                    
                          <div class="major_select">
                              <div class="info-text">
                                <I>{{user_department}}</I>
                              </div>
                          </div>
                      </div>
                    </div>
                    {% if user_sub_department %}
                    <div class="sub_major">
                      <div class="info-title">
                          <div class="title2" id="sub_major">부전공 / 복수전공 &nbsp;|</div>                    
                          <div class="major_select">
                              <div class="info-text">
                                <I>{{user_sub_department}}</I>
                              </div>
                          </div>
                      </div>
                    </div>
                    {% endif %}
                    <div class="grade">
                      <div class="info-title">
                          <div class="title2">학　년 &nbsp;|</div>
                          <span class="info-text">
                            <I>{{profile.year_in_school}}</I>
                          </span>
                      </div>
                    </div>          

                  </div>
                  
                  <div class="text-center">
                    <hr class="my-4">
                    <p class="introduce">— {{profile.introduction}}</p>
                    <!-- <a href="https://www.creative-tim.com/product/argon-dashboard" target="_blank">Show more</a> -->
                    <hr class="my-4">
                    <div class="post_list">
                      <div class="questions">
                        <h4>내가 작성한 질문 목록</h4>
                        {% for question in questions %}
                        <a href="{% url 'qna:detail' question.id %}">
                          <h5>{{ question.title }}</h5>
                        </a>
                        {% endfor %}
                      </div>
                      <div class="answers">
                        <h4>내가 작성한 답변 목록</h4>
                        {% for answer in answers %}
                        <a href="{% url 'qna:detail' answer.question.id %}">
                          <h5>{{ answer.content }}</h5>
                        </a>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  <script src="{% static 'js/profile_js.js' %}" defer></script>
{% endblock %}

users/templates/users/mypage_edit.html
{% extends 'base.html' %}
{% load static %}


{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile_style.css' %}">
<!-- mypage -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="main-content">
      <div class="container mt-7">
        <!-- Table -->
        <!-- <h2 class="mb-5">개인 프로필</h2> -->
        <br>
        <br>
        <div class="box">
          <div class="col-xl-8 m-auto order-xl-2 mb-5 mb-xl-0">
            <div class="card card-profile shadow">
              <div class="row justify-content-center">
                <div class="col-lg-3 order-lg-2">
                  <div class="card-profile-image">
                    <a href="#">
                      {% if profile.image  %}
                      <img src="{{ profile.image.url }}" class="rounded-circle">
                      {% else %}
                      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtB6rXnf0CcbxpTidJShuQWRvubJ-tDJS41O9C8IdKGeKxAk7Bnl2A2Vf-iB3Ef-oskVM&usqp=CAU" class="rounded-circle">
                      {% endif %}
                    </a>
                  </div>
                </div>
              </div>
              <div class="card-body pt-0 pt-md-4_2">
                <form action="{% url 'users:mypage_update' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}  
                    <div class="info">
                        <div class="photo">
                            <div class="info-title">
                                <div class="title2">프로필 이미지 &nbsp;|</div>
                                <div class="info-text">
                                    <I><input type="file" name="profile_image"></I>
                                </div>
                            </div>
                        </div>
                        <div class="nickname">
                            <div class="info-title">
                                <div class="title2">닉네임 &nbsp;|</div>
                                <div class="info-text">
                                    <I><input type="text" style="width:240px;" name="name" value="{% if profile.name %}{{profile.name}}{% endif %}"></I>
                                </div>
                            </div>
                        </div>
                        <div class="major">
                            <div class="info-title">
                                <div class="title2" id="major">전　공 &nbsp;|</div>
                                
                                <div class="major_select">
                                    <div class="info-text">
                                        <I>
                                            <select id="department" name="department" >
                                                <option value="">-- 선택하세요 --</option>
                                                {% for d in department_list %}
                                                <option value="{{ d }}">{{ d }}</option>
                                                {% endfor %}
                                            </select>
                                        </I>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="sub_major">
                            <div class="info-title">
                                <div class="title2" id="sub_major">부전공 / 복수전공 &nbsp;|</div>
                                
                                <div class="major_select">
                                    <div class="info-text">
                                        <I>
                                            <select id="sub_department" name="sub_department" >
                                                <option value="">-- 선택하세요 --</option>
                                                {% for d in sub_department_list %}
                                                <option value="{{ d }}">{{ d }}</option>
                                                {% endfor %}
                                            </select>
                                        </I>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="grade">
                            <div class="info-title">
                                <div class="title2">학　년 &nbsp;|</div>
                                <span class="info-text">
                                <I>
                                    <select id="grade" name="grade">
                                    <option value="">-- 선택하세요 --</option>
                                    <option value="1">1학년</option>
                                    <option value="2">2학년</option>
                                    <option value="3">3학년</option>
                                    <option value="4">4학년</option>
                                    <option value="pg">대학원생</option>
                                    <option value="gr">졸업생</option>    
                                    </select>
                                </I>
                                </span>
                            </div>
                        </div>           
                        <div class="intro">
                            <div class="info-title">
                                <div class="title2">한줄소개 &nbsp;|</div>
                                <div class="info-text">
                                    <I>
                                        <textarea name="intro" id="" cols="30" rows="4" placeholder="한줄 소개를 적어주세요!">{{ profile.introduction }}</textarea>
                                    </I>
                                </div>
                            </div>
                        </div>   
                    </div>
                        <div class="text-center">
                            <button class="submit" type="submit">수정완료</button>
                        </div>
                    </div>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    
  <script src="{% static 'js/profile_js.js' %}" defer></script>
{% endblock %}

users/templates/users/mypage_new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form action="{% url 'users:mypage_create' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <p>프로필 사진 : <input type="file" name="profile_image"></p>
    <p>한줄소개 : <textarea name="intro" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">저장하기</button>
</form>

{% endblock %}