DGin/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('qna/', include('qna.urls')),
    path('accounts/',include('accounts.urls')),
    path('users/',include('users.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/codelion-django-main/5_댓글/blogproject/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),

    # html form 을 이용해 블로그 객체 만들기
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # django form을 이용해 블로그 객체 만들기
    path('formcreate/', views.formcreate, name='formcreate'),

    # django modelform을 이용해 블로그 객체 만들기
    path('modelformcreate/', views.modelformcreate, name='modelformcreate'),

    # 댓글 처리 url
     path('create_comment/<int:blog_id>', views.create_comment , name="create_comment")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/codelion-django-main/6_개발자_대나무숲/devsns/urls.py
from django.contrib import admin
from django.urls import path, include
from snsapp import views
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('freehome/', views.home, name='home'),
    path('postcreate', views.postcreate, name='postcreate'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment'),

    path('login/', accounts_views.login, name='login'),    
    path('logout/', accounts_views.logout, name='logout'),
    path('signup/', accounts_views.signup, name='signup'),

    path('', views.freehome, name='freehome'),
    path('freepostcreate', views.freepostcreate, name='freepostcreate'),
    path('freedetail/<int:post_id>', views.freedetail, name='freedetail'),
    path('new_freecomment/<int:post_id>', views.new_freecomment, name='new_freecomment'),

    path('accounts/', include('allauth.urls')),

]

accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name='signup'),
]

qna/urls.py
from django.urls import path
from .views import *

app_name = "qna"
urlpatterns = [
    path('majorlist/', majorList, name="majorList"),
    path('nonmajorlist/', nonmajorList, name="nonmajorList"),
    
    path('<int:id>', detail, name="detail"),
    path('major_new/', major_new, name="major_new"),
    path('nonmajor_new/', nonmajor_new, name="nonmajor_new"),
    path('major_create/', major_create, name="major_create"),
    path('nonmajor_create/', nonmajor_create, name="nonmajor_create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<str:question_id>/create_answer/', create_answer, name="create_answer"),
    path('<str:question_id>/edit_answer/<str:answer_id>', edit_answer, name="edit_answer"),
    path('<str:question_id>/update_answer/<str:answer_id>', update_answer, name="update_answer"),
    path('<str:question_id>/delete_answer/<str:answer_id>', delete_answer, name="delete_answer"),

    path('<int:id>/likes/', likes, name="likes"),
    path('<int:question_id>/select/<int:answer_id>', select, name="select"),
    path('search/', search, name='search'),
]

users/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = "users"
urlpatterns = [
  path('mypage/', mypage, name="mypage"),
  path('mypage_new/', mypage_new, name="mypage_new"),
  path('mypage_create/', mypage_create, name="mypage_create"),
  path('mypage_edit/', mypage_edit, name="mypage_edit"),
  path('mypage_update/', mypage_update,name="mypage_update"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DGin/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from qna.models import Question, Profile, Department, Answer

def mypage(request):
   #내가 쓴 글 필터링하는 함수
   user_profile = get_object_or_404(Profile, user = request.user)
   questions=Question.objects.filter(writer=user_profile)
   user_department = user_profile.department.all()
   answers=Answer.objects.filter(writer=user_profile)
   count_q = questions.count()
   count_a = answers.count()
   return render(request,'users/mypage.html',{
      'questions':questions,
      'profile':user_profile,
      'user_department':user_department,
      'answers': answers,
      'count_q': count_q,
      'count_a': count_a,
      })


def mypage_new(request):
   return render(request, 'users/mypage_new.html')



# Mypage에 쓴 자신 정보 수정하고 생성하는 함수/수정하면 mypage로 돌아가게
def mypage_create(request):
    new_mypage = get_object_or_404(Profile, user = request.user)
    new_mypage.introduction = request.POST['intro']
    #Profile 모델에서 자기소개를 introduction으로 선언해줬으니까 .introduction으로 불러와야 돼
    new_mypage.image = request.FILES.get('profile_image')
    new_mypage.save()
    return redirect('users:mypage')

def mypage_edit(request):
   #질문 작성 crud에서는 질문의 id를 가져와서 수정했던거에 비해 프로필은 request.user로 현재 로그인된 계정을 불러올수 있으니까 따로 id를 선언해줄 필요 없어   
   departments = Department.objects.all()
   myprofile = get_object_or_404(Profile, user=request.user)
   mine =  myprofile.department.all()
   plus_result = []
   minus_result = []
   for d in departments:
      if d in mine:
         minus_result.append(d)
      else:
         plus_result.append(d)
   return render(request,'users/mypage_edit.html',{
      'plus_departments':plus_result,   
      'minus_departments':minus_result,
      'profile':myprofile,
      })

def mypage_update(request):
   update_mypage = get_object_or_404(Profile, user = request.user)
   update_mypage.introduction = request.POST['intro']
   update_mypage.image = request.FILES.get('profile_image')
   update_mypage.name = request.POST['name']
   if request.POST['plus_department'] != '':
      department = Department.objects.get(name = request.POST['plus_department'])
      update_mypage.department.add(department)
   if request.POST['minus_department'] != '':
      department = Department.objects.get(name = request.POST['minus_department'])
      update_mypage.department.remove(department)
   grade = request.POST['grade']

   FRESHMAN = '1학년'
   SOPHOMORE = '2학년'
   JUNIOR = '3학년'
   SENIOR = '4학년'
   POSTGRAD = '대학원생'
   GRADUATED = '졸업생'
   if grade == "1":
      update_mypage.year_in_school = FRESHMAN
   elif grade == "2":
      update_mypage.year_in_school = SOPHOMORE
   elif grade == "3":
      update_mypage.year_in_school = JUNIOR
   elif grade == "4":
      update_mypage.year_in_school = SENIOR 
   elif grade == "pg":
      update_mypage.year_in_school = POSTGRAD 
   elif grade == "gr":
      update_mypage.year_in_school = GRADUATED
   else :
      pass
   update_mypage.save()
   return redirect('users:mypage')

DGin/templates/shared/_footer.html
<footer style="background-color: #ff9900; color :  #ffffff;
display: flex;
padding: .5rem 2rem;
font-size: 1rem;
font-weight: 300; 
height: 50px">
    비전공자를 위한 코딩 동아리 <a href="http://dgulion.co.kr/">&nbsp멋쟁이 사자처럼&nbsp</a> 4조
</footer>

DGin/templates/shared/_header.html
{% load i18n %}

{% block content %}
<header>

</header>
{% endblock %}

DGin/templates/shared/_navbar.html
{% load static %}
    <!-- Nav Bar -->
<nav class="navbar">
  <div class="navbar__logo">
        <div class="logo">
            <a href="/" style="text-decoration: none; color:white;">
                <div class="image">
                    <img src="{% static 'img/dgin_icon1.png' %}" alt="">
                </div>
                <div class="text" style="color:white;">
                    동국 !N
                </div>
            </a>
        </div>
  </div>
  <ul class="navbar__menu">
      <li>
          <a href="{% url 'qna:majorList' %}" style="text-decoration: none; color:white;">질문게시판</a>
      </li>
      <li>
          <a href="{% url 'qna:nonmajorList' %}" style="text-decoration: none; color:white;">상담게시판</a>
      </li>
  </ul>
  <ul class="navbar__icons">
      <li class="nav-item dropdown">
          {% if user.is_authenticated %}
          <!--로그인시 보이는 화면-->
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:white; text-decoration: none;">
          {{user.username}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'users:mypage' %}" style="text-decoration: none; color:white;">마이페이지</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}" style="text-decoration: none; color:white;">로그아웃</a></li>
          </ul>
          {% else %}
          <!--로그아웃시 보이는 화면-->
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:white; text-decoration: none;">
            <div class="profile_icon">
                <img src="https://icon-library.com/images/profile-icon-white/profile-icon-white-3.jpg" alt="">
            </div>
          </a>
          <ul class="dropdown-menu main-nav" aria-labelledby="navbarDropdown">
            <li><a class="signin" href="#0" style="text-decoration: none; color:white;">로그인</a></li>
            <li><a class="signup" href="#0" style="text-decoration: none; color:white;">회원가입</a></li>
          </ul>
          {% endif %}
      </li>
  </ul>

  <a href="#" class="navbar__toggleBtn">
      <i class="fas fa-bars"></i>
  </a>
</nav>
<!-- Nav bar -->