DGin/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('qna/', include('qna.urls')),
    path('accounts/',include('accounts.urls')),
    path('users/',include('users.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/codelion-django-main/5_댓글/blogproject/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),

    # html form 을 이용해 블로그 객체 만들기
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),

    # django form을 이용해 블로그 객체 만들기
    path('formcreate/', views.formcreate, name='formcreate'),

    # django modelform을 이용해 블로그 객체 만들기
    path('modelformcreate/', views.modelformcreate, name='modelformcreate'),

    # 댓글 처리 url
     path('create_comment/<int:blog_id>', views.create_comment , name="create_comment")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/codelion-django-main/6_개발자_대나무숲/devsns/urls.py
from django.contrib import admin
from django.urls import path, include
from snsapp import views
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('freehome/', views.home, name='home'),
    path('postcreate', views.postcreate, name='postcreate'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment'),

    path('login/', accounts_views.login, name='login'),    
    path('logout/', accounts_views.logout, name='logout'),
    path('signup/', accounts_views.signup, name='signup'),

    path('', views.freehome, name='freehome'),
    path('freepostcreate', views.freepostcreate, name='freepostcreate'),
    path('freedetail/<int:post_id>', views.freedetail, name='freedetail'),
    path('new_freecomment/<int:post_id>', views.new_freecomment, name='new_freecomment'),

    path('accounts/', include('allauth.urls')),

]

qna/urls.py
from django.urls import path
from .views import *

app_name = "qna"
urlpatterns = [
    path('majorlist/', majorList, name="majorList"),
    path('nonmajorlist/', nonmajorList, name="nonmajorList"),
    
    path('<int:id>', detail, name="detail"),
    path('major_new/', major_new, name="major_new"),
    path('nonmajor_new/', nonmajor_new, name="nonmajor_new"),
    path('major_create/', major_create, name="major_create"),
    path('nonmajor_create/', nonmajor_create, name="nonmajor_create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<str:question_id>/create_answer/', create_answer, name="create_answer"),
    path('<str:question_id>/edit_answer/<str:answer_id>', edit_answer, name="edit_answer"),
    path('<str:question_id>/update_answer/<str:answer_id>', update_answer, name="update_answer"),
    path('<str:question_id>/delete_answer/<str:answer_id>', delete_answer, name="delete_answer"),

    path('<int:id>/likes/', likes, name="likes"),
    path('<int:question_id>/select/<int:answer_id>', select, name="select"),
    path('search/', search, name='search'),
]

qna/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

#교수
class Professor(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

#학과
class Department(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


#전공(수업)
class Major(models.Model):
    name = models.CharField(max_length=20)
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='majors')
    id = models.AutoField(primary_key=True)
    def __str__(self):
        return self.name


#개인프로필, auth의 User를 일대일 필드로 가짐
class Profile(models.Model):
    name = models.CharField(max_length=20, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    image = models.ImageField(upload_to = "image/", blank=True, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True, related_name="department")
    sub_department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True, related_name="sub_department")
    introduction = models.TextField(max_length=300, blank=True, null=True)

    FRESHMAN = '1학년'
    SOPHOMORE = '2학년'
    JUNIOR = '3학년'
    SENIOR = '4학년'
    POSTGRAD = '대학원생'
    GRADUATED = '졸업생'
    YEAR_IN_SCHOOL_CHOICES = [
        (FRESHMAN, '1학년'),
        (SOPHOMORE, '2학년'),
        (JUNIOR, '3학년'),
        (SENIOR, '4학년'),
        (POSTGRAD, '대학원생'),
        (GRADUATED, '졸업생'),
    ]
    year_in_school = models.CharField(
        max_length=10,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )


    def is_upperclass(self):
        return self.year_in_school in (self.JUNIOR, self.SENIOR)

    def __str__(self):
        return self.name


#질문
class Question(models.Model):
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    major = models.ForeignKey(Major, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to = "question/", blank=True, null=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='like_questions')
    
    def __str__(self):
        return self.title

    def title_short(self):
        return f"{self.title[:12]}..."
    
    def summary_short(self):
        return f"{self.body[:40]}..."

    def summary_long(self):
        return f"{self.body[:240]}..."

    def like_counts(self):
        return self.like_users.count()

#질문에 업로드하는 이미지(미완성)
class QuestionImage(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    image = models.ImageField(default='media/diary/default_image.jpeg', upload_to='diary', blank=True, null=True)      

#답변
class Answer(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    created_at = models.DateTimeField()
    image = models.ImageField(upload_to = "answer/", blank=True, null=True)
    selection = models.BooleanField(default = False)

    def __str__(self):
        return self.content[:20]

qna/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Professor, Department, Major, Question, Answer, Profile
from django.utils import timezone
from django.db.models import Q
# Create your views here.

def majorList(request):
    try :
        #현재 로그인한 user의 profile을 가져옵니다.
        user_profile = get_object_or_404(Profile, user = request.user)
        #profile에서 학과를 불러옵니다.(여러개일수도 있어서 all 사용)
        user_department = user_profile.department
        user_sub_department = user_profile.sub_department
        #질문글을 담을 리스트
        questions_list = []
        #학과의 전공들을 가져옵니다.
        d_majors = Major.objects.filter(department=user_department)
        sub_majors = Major.objects.filter(department=user_sub_department)
        for m in d_majors:
            questions = Question.objects.filter(major = m)
            #질문들을 리스트에 반복문으로 집어넣습니다.
            for q in questions:
                questions_list.append(q)
        for m in sub_majors:
            questions = Question.objects.filter(major = m)
            #질문들을 리스트에 반복문으로 집어넣습니다.
            for q in questions:
                questions_list.append(q)
        #질문들이 들어있는 리스트를 시간순으로 정렬합니다.(order_by는 queryset형태가 아니라 쓸 수 없음)
        questions_list = sorted(questions_list, key=lambda x: x.pub_date)

        done_wait = False

        questions_result = []
        #post 요청(답변을 기다리는 질문/채택 완료된 질문)이 들어오면
        if request.method == 'POST':
            #채택완료된 질문만 보여준다
            if request.POST['selection'] == "done":
                done_wait = True
                for q in questions_list:
                    #한 질문의 모든 답변 불러오기
                    answers = q.answers.all()
                    #답변에 채택 완료된게 있으면, 최종 리스트에 질문을 추가한다.
                    for a in answers:
                        if a.selection == True:
                            questions_result.append(q)

            #답변을 기다리는 질문만 보여준다
            elif request.POST['selection'] == "wait":
                for q in questions_list:
                    questions_result.append(q)
                for q in questions_list:
                    answers = q.answers.all()
                    for a in answers:
                        if a.selection == True:
                            questions_result.remove(q)
        #get요청 > 채택 여부 상관없이 전부 보여줌 > questions가 최종 결과물
        else :
            questions_result = questions_list

        return render(request, 'qna/majorList.html', {
            'questions':questions_result,
            'departments':user_department,
            'if_done_wait': done_wait,
        })
    except :
        return render(request, 'qna/majorList.html')

def nonmajorList(request):
    #전공이 없는 질문들을 시간순 정렬
    questions = Question.objects.filter(major = None).order_by('-pub_date')
    #최종 질문들을 넣을 리스트 생성
    questions_result = []
    #post 요청(답변을 기다리는 질문/채택 완료된 질문)이 들어오면
    done_wait = False
    if request.method == 'POST':
        #채택완료된 질문만 보여준다
        if request.POST['selection'] == "done":
            done_wait = True
            for q in questions:
                #한 질문의 모든 답변 불러오기
                answers = q.answers.all()
                #답변에 채택 완료된게 있으면, 최종 리스트에 질문을 추가한다.
                for a in answers:
                    if a.selection == True:
                        questions_result.append(q)
        #답변을 기다리는 질문만 보여준다
        elif request.POST['selection'] == "wait":
            for q in questions:
                questions_result.append(q)
            for q in questions:
                answers = q.answers.all()
                for a in answers:
                    if a.selection == True:
                        questions_result.remove(q)
    #get요청 > 채택 여부 상관없이 전부 보여줌 > questions가 최종 결과물
    else :
        questions_result = questions

    return render(request, 'qna/nonmajorList.html', {
        'questions':questions_result,
        'if_done_wait': done_wait,
    })

def detail(request, id):
    question = get_object_or_404(Question, pk = id)
    all_answers = question.answers.all().order_by('created_at')
    if_q_solved = False
    comments_count = question.answers.count()
    try:
        user_profile = get_object_or_404(Profile, user = request.user)

        for a in all_answers:
            if a.selection == True:
                if_q_solved = True
        question_writer = question.writer

        return render(request, 'qna/detail.html', {
            'question':question, 
            'answers':all_answers,
            'if_q_solved':if_q_solved,
            'question_writer': question_writer,
            'user_profile':user_profile,
            'comments_count' : comments_count,
            })
    except:
        return redirect('accounts:login')

def major_new(request):
    #현재 로그인한 user의 profile을 가져옵니다.
    user_profile = get_object_or_404(Profile, user = request.user)
    #profile에서 학과를 불러옵니다.(여러개일수도 있어서 all 사용)
    user_department = user_profile.department
    user_sub_department = user_profile.sub_department
    user_major_list = []
    user_majors = Major.objects.filter(department=user_department)
    for m in user_majors: 
        user_major_list.append(m)
    user_majors = Major.objects.filter(department=user_sub_department)
    for m in user_majors: 
        user_major_list.append(m)
    user_major_list = sorted(user_major_list, key=lambda x: x.name)
    return render(request, 'qna/major_new.html', {
        'majors': user_major_list,
    })


def nonmajor_new(request):
    return render(request, 'qna/nonmajor_new.html')

def major_create(request):
    new_question = Question()
    new_question.title = request.POST['title']
    user_profile = get_object_or_404(Profile, user = request.user)
    new_question.writer = user_profile
    new_question.pub_date = timezone.now()
    new_question.body = request.POST['body']
    new_question.image = request.FILES.get('image')
    new_question.major = get_object_or_404(Major, id = request.POST['major'])
    new_question.save()
    return redirect('qna:detail', new_question.id)

def nonmajor_create(request):
    new_question = Question()
    new_question.title = request.POST['title']
    user_profile = get_object_or_404(Profile, user = request.user)
    new_question.writer = user_profile
    new_question.pub_date = timezone.now()
    new_question.body = request.POST['body']
    new_question.image = request.FILES.get('image')
    new_question.major = None
    new_question.save()
    return redirect('qna:detail', new_question.id)

def edit(request, id):
    edit_question = Question.objects.get(id = id)
    #현재 로그인한 user의 profile을 가져옵니다.
    user_profile = get_object_or_404(Profile, user = request.user)
    #profile에서 학과를 불러옵니다.(여러개일수도 있어서 all 사용)
    user_department = user_profile.department
    user_sub_department = user_profile.sub_department
    user_major_list = []
    user_majors = Major.objects.filter(department=user_department)
    for m in user_majors: 
        user_major_list.append(m)

    user_majors = Major.objects.filter(department=user_sub_department)
    for m in user_majors: 
        user_major_list.append(m)
    q_major = edit_question.major
    nonmajor = False
    if q_major != None:
        user_major_list.remove(q_major)
    else:
        nonmajor = True
    return render(request, 'qna/edit.html', {
        'question' : edit_question,
        'majors': user_major_list,
        'q_major': q_major,
        'nonmajor': nonmajor,
        })

def update(request, id):
    update_question = Question.objects.get(id=id)
    update_question.title = request.POST['title']
    user_profile = get_object_or_404(Profile, user = request.user)
    update_question.writer = user_profile
    update_question.pub_date = timezone.now()
    update_question.body = request.POST['body']
    update_question.image = request.FILES.get('image')
    try :
        if request.POST['major'] == 'nothing':
            pass
        else:
            update_question.major = get_object_or_404(Major, id = request.POST['major'])
    except: 
        update_question.major = None
    update_question.save()
    return redirect('qna:detail', update_question.id)

def delete(request , id):
    delete_question = Question.objects.get(id = id)
    delete_question.delete()
    return redirect('main:landing')

def create_answer(request, question_id):
    new_answer = Answer()
    user_profile = get_object_or_404(Profile, user = request.user)
    new_answer.writer = user_profile
    new_answer.content = request.POST['content']
    new_answer.created_at = timezone.now()
    new_answer.question = get_object_or_404(Question, pk=question_id)
    new_answer.image = request.FILES.get('image')
    new_answer.save()
    return redirect('qna:detail', question_id)

def edit_answer(request, question_id, answer_id):
    target_question = Question.objects.get(id = question_id)
    edit_answer = Answer.objects.get(id = answer_id)
    return render(request, 'qna/edit_answer.html', {'question':target_question, 'answer' : edit_answer})

def update_answer(request, question_id, answer_id):
    target_question = Question.objects.get(id = question_id)
    update_answer = Answer.objects.get(id = answer_id)
    update_answer.content = request.POST['content']
    user_profile = get_object_or_404(Profile, user = request.user)
    update_answer.writer = user_profile
    update_answer.image = request.FILES.get('image')
    update_answer.save()
    return redirect('qna:detail', target_question.id)
  
def delete_answer(request , question_id, answer_id):
    target_question = Question.objects.get(id = question_id)
    delete_answer = Answer.objects.get(id = answer_id)
    delete_answer.delete()
    return redirect('qna:detail', target_question.id)

def likes(request, id):
    if request.user.is_authenticated:
        question = get_object_or_404(Question, pk=id)

        if question.like_users.filter(pk=request.user.pk).exists():
            question.like_users.remove(request.user)
        else:
            question.like_users.add(request.user)

qna/templates/qna/detail.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/detail_style.css' %}">
{% endblock %}

{% block content %}
<section>
    <div class="question">
        <div class="data1">
        {% if question.major %}
        <p class="major" style="align-items: left;">전공 | {{ question.major }} </p>
        <p class="professor" style="align-items: right;">교수 | {{ question.major.professor }}</p>
                {% endif %}</div>
        <div class="title">
        {{question.title}}</div>

        <div class="answer">
            <p>{{question.body}}</p></div>

        {% if question.image %}
            <div class="picBox pd56">
                <div class="pic">
                    <p><img src="{{ question.image.url }}" alt="사진" style="width: 500px;"></p>
                </div>
            </div>
        {% endif %}

        <div class="data2">
            {% if question.writer %}
                작성자 | {{ question.major.department }} {{ question.writer }}
            {% else %}
                작성자 | 알 수 없음
            {% endif %}<br>
            작성일 | {{ question.pub_date }}
        </div>

            <form action="{%url 'qna:likes' question.id%}" method="POST">
                <div class="idk">			
                {%csrf_token%}
                {% if user in question.like_users.all %}	
                <button type="submit" style="border: none;"><a class="btn btn-orange">나도몰라요 취소  {{ question.like_counts }}</a></button>		
                {% else %}
                <button type="submit" style="border: none;"><a class="btn btn-orange">나도몰라요  {{ question.like_counts }}</a></button>		
                {% endif %}</div>
            </form>
        
        <br>
            {% if question.writer == user_profile %}
            <a href="{% url 'qna:edit' question.id %}"><strong>수정하기 &nbsp</strong></a>
            <a href="{% url 'qna:delete' question.id %}"><strong>삭제하기</strong></a>
            {% endif %}
        <hr>

        {% if user.is_authenticated %}
        <div class="solver">
            <form action="{%url 'qna:create_answer' question.id%}" method="POST" enctype="multipart/form-data">
                {%csrf_token%}
                <textarea name="content" placeholder="문제의 답을 해결해주세요!"></textarea>
                <div class="filebox">
                    <input class="upload-name" value="파일선택" disabled="disabled">
                    <label for="ex_filename">업로드</label> 
                    <input type="file" name="image" id="ex_filename" class="upload-hidden"> 
                </div>
                <div class="submit_button">			
                    <button type="submit" style="border: none;"><a class="btn btn-orange">확인</a></button>		
                </div>
            </form>
        </div>
        
        {% else %}
        <h3>답변을 올리려면 로그인을 해 주세요.</h3>

        {% endif %}
        <br><hr>
        <div>
            {% for answer in answers %}
            <div class="comment">
                {{answer.content}}</div>
            <div>
                <div class="data2">
                    {% if question.writer %}
                        작성자 | {{ question.major.department }} {{ answer.writer.year_in_school }} {{answer.writer}}
                    {% else %}
                        작성자 | 알 수 없음
                    {% endif %}<br>
                    작성일 | {{ answer.created_at }}
                </div>
                {% if answer.selection is True %}
                <h4>채택완료</h4>
                {% endif %}
                {% if answer.image %}
                <div class="picBox pd56">
                    <div class="pic">
                        <p><img src="{{ answer.image.url }}" alt="사진" style="width: 500px;"></p>
                    </div>
                </div>
                <br>
                {% endif %}
                {% if answer.writer == user_profile %}
                <a href="{% url 'qna:edit_answer' question.id answer.id %}"><strong>수정하기</strong></a>
                <a href="{% url 'qna:delete_answer' question.id answer.id %}"><strong>삭제하기</strong></a>
                {% endif %}

                {% if question_writer == user_profile %}

                    {% if if_q_solved == False %}
                    <form action="{%url 'qna:select' question.id answer.id %}" method="post">
                        {%csrf_token%}
                        {% if answer.selection == False %}
                        <button type = "radio" name="select" value="True">답변 채택하기</button>
                        <!-- <a href="" class="user_select" name="select" value="True">답변 채택하기</a> -->
                        {% else %}
                        <button type = "radio" name="select" value="False">다른 답변 기다리기</button>
                        {% endif %}
                    </form>
                    {% else %}
                    
                    {% if answer.selection == True %}
                    <form action="{%url 'qna:select' question.id answer.id %}" method="post">
                        {%csrf_token%}
                        <button type = "radio" name="select" value="False">채택 취소하기</button>
                    </form>
                    {% endif %}
                    {% endif %}

                {% endif %}

                <br>
            </div>
            {% endfor %}
        </div>  
    </div>
</section>
<script src="{% static 'js/que_new.js' %}" defer="defer"></script>
{% endblock %}

qna/templates/qna/edit.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}
<link rel="stylesheet" type="text/css" href="{% static 'css/que_new.css' %}">
{% endblock %}

{% block content %}

<section class="new">
    <div class="question"><h1>질문 수정하기</h1></div>
    <form action="{%url 'qna:update' question.id %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {% if nonmajor == False %}
        <div class="select_major">
            <label for="subject">
            과목선택
            </label>
            <select name="major">
                <option value="nothing">{{q_major}} - {{q_major.professor}}</option>
                {% for m in majors %}
                <option value="{{ m.id }}">{{ m }} - {{ m.professor }}</option>
                {% endfor %}
            </select>
        </div>
        {% endif %}
        <textarea type="text" name="title" id="title" style="font-size:14pt" placeholder="{{ question.title }}">{{ question.title }}</textarea>
        <!-- <p><input type="file" id="image"></p> -->
        <div class="filebox">
            <input class="upload-name" value="파일선택" disabled="disabled">

            <label for="ex_filename">업로드</label> 
            <input type="file" name="image" id="ex_filename" class="upload-hidden"> 
        </div>
        <p><textarea type="text" name="body" class='autoExpand' rows='3' data-min-rows='3' placeholder='내용을 입력하세요' style="font-size:14pt" autofocus>{{ question.body }}</textarea></p>
        
        <!-- <div class="submit_botton"><button type = "submit">제출</button></div> -->
        <div class="submit_button">			
            <button type="submit" style="border: none;"><a class="btn btn-orange">물어보기</a></button>		
        </div>
    </form>
</section>
<script src="{% static 'js/que_new.js' %}" defer="defer"></script>
{% endblock %}

qna/templates/qna/majorList.html
{% extends 'base.html' %}
{% load static %}
{% block style&js %}

<link rel="stylesheet" href="{% static 'css/major_q_style.css' %}">
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Rufina:400,700|Source+Sans+Pro:200,300,400,600,700" rel="stylesheet">

{% endblock %}

{% block content %}
<div id="site__bg"></div>
<div class="main">

<!-- Left Title -->
<section class="site">
    <h1 class="site__title site__title--separator">전공 질문</h1>
    {% if if_done_wait %}
    <p class="site__description">답변이 완료된 질문들입니다.</p>
    {% else %}
    <p class="site__description">답변을 기다리는 질문들이 있어요!</p>
    {% endif %}
</section>

{% if user.is_authenticated %}
<!-- Left Title -->
<section class="make_question">
    <div class="new" style="text-align: center;">
        <h4 style="min-height: 15%;"><a href="{%url 'qna:major_new'%}" style="color: black; align-items: center;">질문하기 &rarr;</a></h4>
    </div>
</section>
<!-- Right Questions -->
<section class="question_menu" style="float: center; padding-left:20px">
    <div class="search-wrapper2" style="float: left;">
        <form action="{% url 'qna:search' %}" method="GET">
            {% csrf_token %}
            <div class="input-holder">
                <input name="search" type="text" class="search-input" placeholder="무엇이든 물어보세요!" />
                <button type="submit" class="search-icon">
                    <img src="{% static 'img/search.png' %}" alt="">
                </button>
            </div>
        </form>
    </div>

    <div class="selection" style="position: relative; float: center; display: flex;">
        <form class="selectionForm" action="{%url 'qna:majorList' %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
                <input id="wait" type = "radio" name="selection" value="wait"> 
                <button type="submit">
                    <label for="wait">답변대기중</label>
                </button>
                <input id="done" type = "radio" name="selection" value="done">
                <button type="submit">
                    <label for="done">답변완료</label>
                </button>
        </form>
    </div>
</section>
    

<section class="episodes">

    <!-- CARD -->
    <div class="body-slide">
        <div class="card-slide2">
            <input type="radio" name="dot" id="one">
            <input type="radio" name="dot" id="two">
            <div class="main-card">
                <div class="cards">
                    
                {% for q in questions %}
                    <div class="card">
                        <div class="questionBox">
                            <span class="job">{{ q.like_counts }}명이 몰라요!</span>
                            <div>
                                {% if q.major %}
                                <div class="major" style="text-align:left;">{{ q.major }}<br>{{ q.major.professor }} 교수님</div>
                                <div class="professor" style="text-align:left;"></div>
                                {% else %}
                                <div class="major" style="text-align:left; padding:15px 0">상담</div>
                                {% endif %}
                                <hr>
                            </div>
                        </div>
                        <div class="content">
                            <a href="{% url 'qna:detail' q.id %}">
                                <div class="details">
                                    <div class="middle">
                                        <div class="job">{{ q.title_short }}</div>
                                        <div class="name">{{ q.writer }}</div>
                                        {% if q.image %}
                                        <div class="text1">{{ q.summary_short }}</div>
                                        <div class="img">
                                            <img src="{{ q.image.url }}" alt="">
                                        </div>
                                        {% else %}
                                        <div class="text2">{{ q.summary_long }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="down">
                                        <hr>
                                        <span class="job2">답변수 [{{ q.answers.count }}] </span>
                                        <span class="date" style="float:right;">{{ q.pub_date }}</span>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}    
                </div>
            </div>
        </div>
    </div>


</section>
<!-- Right Questions -->
{% else %}
<style>
    .nonmessage {
        height: 400px;
        overflow: hidden;
    }

    .nonmessage .text{
        margin: 0 auto;
        text-align: center;
    }
    .account_button {
        width: 100%;
        max-width: 300px;
        margin: 0 auto;
        height: 500px;
        cursor: pointer;
    }
    .account_button ul {
        position: absolute;
      width: 50%;
        top: 55%;
        margin: 0;
        padding: 0;
    }
    .account_button li {
        list-style: none;
        float: left;
    }
    .account_button a {
      display: block;
      height: 50px;
        margin: 10px;
        padding: 2px 35px;
        text-decoration: none;
        border-radius: 30px;
      line-height: 45px;
      color: #FFF;
        -webkit-transition: all 0.30s ease-in-out;
          -moz-transition: all 0.30s ease-in-out;
          -ms-transition: all 0.30s ease-in-out;
          -o-transition: all 0.30s ease-in-out;
    }
    .account_button li:nth-child(1) a {
        background: #ffc739;
        border: 2px solid #fff;
    }
    .account_button li:nth-child(1) a:hover {
        background : #ff9a00;
        color: #ffc739;
    }
    
    .account_button li:nth-child(2) a {
      background: #ffc739;
        border: 2px solid #fff;
    }
    .account_button li:nth-child(2) a:hover {
        background: #ff9a00;
        border: 2px solid #fff;
    }
    </style>
<div class="nonmessage">
    <div class="text">
        <h4>질문게시판 메뉴는 로그인 후 이용 가능합니다.</h4>
    </div>       
    <div class="main-nav account_button">
        <ul>
            <li><a class="signin" href="#0">로그인</a></li>
            <li><a class="signup" href="#0">회원가입</a></li>
        </ul>
    </div>
</div>
{% endif %}

</div>


{% endblock %}